---
version: "3"

services:

  nginx:
    image: nginx:1.22.1
    ports:
    - 8080:8080
    - 8181:80
    volumes:
    - ./nginx/status.conf:/etc/nginx/conf.d/status.conf
    # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    # - ./nginx/myapp.conf:/etc/nginx/conf.d/default.conf
    # - ./test-access.log:/var/log/nginx/access.log