{
 "title": "Web API",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "path", "query": { "query": "label_values(path)" } },
   { "name": "codes", "query": { "query": "label_values(status_code)" } }
  ]
 },
 "panels": [
  {
   "title": "RPS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(nginx_http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "sum by(path) (rate(nginx_http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (path) (rate(nginx_http_request_duration_seconds_sum{status_code=~\"2..\"}[5m])) / sum  by (path) (rate(nginx_http_request_duration_seconds_count{status_code=~\"2..\"}[5m])) * 1000"
    }
   ]
  },
  {
   "title": "Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (status_code) (rate(nginx_http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total{status_code =~ \"4..|5..\"}[1m])) by (path) / sum(rate(nginx_http_requests_total[1m]))  by (path) * 100"
    }
   ]
  },
  { "title": "Server metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CPU usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[1m]) * 100)"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 4, "y": 17 },
   "targets": [
    {
     "expr": "100 - rate(node_cpu_seconds_total{mode=\"idle\"}[1m]) * 100"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 -((node_memory_MemFree_bytes + node_memory_Cached_bytes) / node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - rate(node_cpu_seconds_total{mode=\"idle\"}[1m]) * 100"
    }
   ]
  },
  {
   "title": "HDD usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - sum(node_filesystem_free_bytes) / sum(node_filesystem_size_bytes) * 100"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 -((node_memory_MemFree_bytes + node_memory_Cached_bytes) / node_memory_MemTotal_bytes) * 100"
    }
   ]
  }
 ]
}